// Casos originales de práctica. Referencias: páginas físicas del PDF, no folios impresos.
const q = (tema, pregunta, opciones, correcta, explicacion, paginas) => ({tema,pregunta,opciones,correcta,explicacion,paginas});
export const examenes = [
{semana:5,titulo:'Componentes y patrones GoF',archivo:'Semana5-Componentes-y-Patrones-GoF.pdf',preguntas:[
q('Strategy','Una fintech calcula intereses con algoritmos distintos según el producto. Cada nuevo algoritmo obliga a ampliar un if/else. ¿Qué patrón permite sustituir el cálculo?', ['Facade','Strategy','Observer','Builder'],1,'Strategy encapsula cada algoritmo detrás del mismo contrato y lo inyecta en el consumidor. Factory atiende la creación de objetos; aquí cambia el comportamiento de cálculo.',[21,25]),
q('Factory','Desembolso y cobranza repiten new CreditoPersonal y new CreditoGrupal. El problema es decidir qué objeto crear. ¿Qué solución del material usarías?',['Observer','Decorator','Factory Method / fábrica de créditos','Strategy para notificar'],2,'La fábrica concentra la selección e instanciación y devuelve el contrato Credito. El PDF denomina Factory Method a su fábrica con switch; técnicamente ese ejemplo corresponde a una fábrica simple. El Factory Method clásico permite que subclases especialicen el método creador.',[15]),
q('Builder','Un plan de amortización recibe diez parámetros, algunos opcionales, y se confunden plazo y día de pago. ¿Qué patrón encaja?',['Builder','Observer','Facade','Singleton'],0,'Builder expresa la construcción por pasos con nombres como conPlazo y conDiaPago. construir valida que el resultado esté completo y respete sus invariantes. No sustituye la validación de dominio.',[16]),
q('Decorator','Una cuota admite seguro, mora y gastos combinables. Aparecen clases para cada combinación. ¿Cómo evitarías esa proliferación?',['Crear más subclases','Hacer todo global','Observer','Decorator'],3,'Decorator envuelve un componente y conserva su interfaz, agregando responsabilidades por composición. Las reglas y el orden de cargos deben seguir el dominio; el patrón por sí mismo no define la prelación de pagos.',[18]),
q('Facade','Tres pantallas repiten la coordinación de desembolsos, recuperaciones, mora, cartera en riesgo y castigos para generar un cierre. ¿Qué usarías?',['Builder','Facade','Decorator','Prototype'],1,'Una fachada ofrece generarCierre(fecha) y coordina colaboradores. No debe absorber sus cálculos: estos permanecen en componentes especializados. El material exige presentar cartera en riesgo junto con castigos.',[19]),
q('Observer','Al entrar una cuota en mora deben reaccionar auditoría, tablero y notificaciones, sin que el motor conozca sus clases concretas. ¿Qué patrón usarías?',['Factory','Builder','Observer','Facade'],2,'Observer permite suscribir receptores a un evento mediante una interfaz común. Agregar un receptor no obliga a modificar el motor. Esto no garantiza por sí solo entrega durable ni ejecución exactamente una vez.',[22]),
q('Cohesión','GestorCredito calcula interés, genera PDF, envía correo y consulta divisas. ¿Qué diagnóstico y mejora corresponden?',['Baja cohesión; separar responsabilidades e inyectar interfaces','Alta cohesión porque todo está en una clase','Falta un Singleton global','Basta cambiar nombres'],0,'Son motivos de cambio distintos dentro de un solo componente. Separar CalculadoraInteres, GeneradorContrato, NotificadorCorreo y ConsultorTipoCambio facilita modificar y reutilizar cada responsabilidad.',[9,11]),
q('Acoplamiento','Un servicio cambia directamente el saldo interno de otro componente. ¿Cómo reducirías el acoplamiento?',['Compartir más variables globales','Hacer públicas todas las propiedades','Pasar una bandera por cada caso','Exponer operaciones de dominio mediante un contrato'],3,'Acceder al estado interno produce acoplamiento por contenido. Un contrato explícito oculta la implementación y permite que el componente proteja sus invariantes.',[8,10]),
q('Refactorización','Al sustituir un condicional por Strategy, los resultados de créditos existentes cambian. ¿Es una refactorización correcta?',['Sí, siempre que haya más clases','No: debe preservar el comportamiento observable','Sí, si compila','Sí, si se borran las pruebas antiguas'],1,'Refactorizar cambia la estructura sin cambiar el comportamiento observable. Primero hay que conservar resultados y contratos, usando las pruebas existentes como red de seguridad; agregar una nueva política es un cambio funcional separado.',[24]),
q('Code smells','Una modificación de tasas exige editar muchos módulos consumidores. ¿Qué señal observas?',['Alta cohesión','Inmutabilidad','Shotgun Surgery y acoplamiento','Uso correcto de Builder'],2,'Un cambio disperso indica que la responsabilidad no está bien localizada. Encapsular la política detrás de una interfaz reduce la propagación. El patrón se elige por el problema identificado, no para aumentar el número de clases.',[25,26]),
q('Clasificación','¿Qué grupo clasifica correctamente Builder, Decorator y Observer?',['Creacional, estructural, comportamiento','Estructural, creacional, comportamiento','Comportamiento, estructural, creacional','Los tres creacionales'],0,'Builder organiza la creación; Decorator compone objetos; Observer distribuye reacciones a eventos. El catálogo tiene 5 patrones creacionales, 7 estructurales y 11 de comportamiento.',[13,23]),
q('Criterio de diseño','Una función sencilla y estable tiene una sola implementación. El equipo propone seis patrones sin un problema concreto. ¿Qué recomendarías?',['Usarlos para demostrar conocimiento','Crear una jerarquía por cada dato','Convertir todo en Singleton','Mantener la simplicidad y justificar cada patrón por una necesidad'],3,'El material advierte contra la sobreingeniería. Un patrón es una estructura útil para un problema recurrente, no una obligación ni un reemplazo del análisis.',[12])]},
{semana:6,titulo:'APIs, contratos y OpenAPI',archivo:'Semana6-Presentacion-APIs-Contratos-OpenAPI.pdf',preguntas:[
q('Contrato','Antes de registrar un pago se exige un monto positivo; después debe existir un solo registro; el capital nunca debe ser negativo. ¿Cómo se clasifican?',['Tres poscondiciones','Precondición, poscondición e invariante','Tres errores HTTP','Invariante, precondición y poscondición'],1,'La precondición obliga a quien llama; la poscondición describe lo garantizado al terminar; la invariante debe sostenerse antes y después. El contrato debe documentar también los errores.',[4]),
q('Idempotencia','Se procesa un pago de Q500, pero se pierde la respuesta. ¿Qué debe conservar el cliente al reintentar?',['Un UUID nuevo cada vez','El ETag de cualquier recurso','La misma Idempotency-Key y el mismo cuerpo','Solo la fecha del dispositivo'],2,'La clave identifica la intención de pago y se reutiliza en sus reintentos. El servidor conserva la respuesta y la huella del cuerpo para no aplicar el movimiento nuevamente.',[13,14]),
q('Conflicto','Una clave ya usada para Q500 vuelve con un cuerpo que solicita Q700. Según el contrato de clase, ¿qué corresponde?',['409 sin sobrescribir la operación anterior','Cobrar la diferencia automáticamente','200 y reemplazar el resultado','Crear otro pago'],0,'Una clave ya representa una operación concreta. Si cambia la huella del cuerpo, se rechaza con conflicto. Reutilizarla para otra intención ocultaría un error del cliente.',[14]),
q('Concurrencia','Dos asesores leen una política v7. Uno guarda v8 y el otro envía If-Match: v7. ¿Qué evita perder el primer cambio?',['Reintentar sin condiciones','Usar GET para escribir','Una clave nueva de pago','ETag / If-Match y rechazo 412'],3,'El bloqueo optimista verifica la versión usada como base de la escritura. El segundo asesor debe recargar y resolver el conflicto. La idempotencia atiende duplicados, no actualizaciones perdidas.',[15]),
q('HTTP','¿Qué afirmación distingue seguridad e idempotencia?',['PUT es seguro porque es idempotente','GET es seguro e idempotente; PUT es idempotente, pero modifica estado','POST siempre es idempotente','DELETE es seguro'],1,'Seguro significa no solicitar una modificación del estado del recurso. Idempotente significa que repetir tiene el mismo efecto pretendido que hacerlo una vez; no exige respuestas idénticas en todos los intentos.',[11]),
q('Dinero','¿Cómo debe viajar Q1,011.88 en el contrato del curso?',['Como float sin moneda','Como texto libre con símbolo','Como {valor: "1011.88", moneda: "GTQ"}','Como 101188 sin documentar unidad'],2,'La cadena conserva la representación decimal y la moneda hace explícita la unidad. El receptor debe usar aritmética decimal o centavos enteros y validar la moneda; convertirlo enseguida a flotante pierde esa protección.',[19]),
q('Errores','Una API devuelve 200 con exito:false y un mensaje ambiguo. ¿Cómo mejorarías su contrato?',['Estado HTTP adecuado y Problem Details','Siempre 500','Eliminar el mensaje','Enviar el stack trace completo'],0,'El código HTTP debe representar la falla y el cuerpo uniforme application/problem+json permite identificar y explicar el problema. Un 200 engaña a clientes y observabilidad; un stack trace expone detalles internos.',[16,17]),
q('Versionado','¿Qué cambio rompe un contrato incluso si el JSON mantiene la misma forma?',['Agregar un endpoint','Agregar un filtro opcional','Agregar un campo opcional tolerado','Cambiar saldo de total adeudado a solo capital'],3,'Cambiar el significado puede corromper reportes sin producir un error sintáctico. El material lo identifica como especialmente peligroso: hay que gobernar y comunicar la evolución del contrato.',[20,21]),
q('Recursos','¿Qué ruta representa mejor el registro de un pago sobre un crédito?',['GET /registrarPago','POST /creditos/C-004/pagos','GET /creditos/C-004/pagos?cobrar=si','POST /hacerTodo'],1,'La ruta identifica recursos y el método expresa la operación. Registrar un pago cambia estado y no debe implementarse como una consulta GET.',[9,10,11]),
q('OpenAPI','El contrato repite el esquema Dinero en diez operaciones. ¿Qué usarías?',['Diez copias manuales','Un comentario sin esquema','components/schemas y referencias $ref','Solo una imagen del JSON'],2,'Los componentes reutilizables evitan divergencias. OpenAPI describe el contrato de la API en un formato procesable; no implementa por sí mismo reglas de negocio ni persistencia.',[25,26]),
q('Contract-first','Frontend y backend interpretan distinto un pago. ¿Qué práctica reduce ese desacuerdo antes de programar?',['Acordar primero petición, respuesta y errores del contrato','Esperar a producción','Documentar únicamente el código ya terminado','Compartir solo capturas'],0,'Contract-first acuerda expectativas explícitas y permite trabajar con simulaciones. Aun así, hay que verificar que la implementación cumpla el contrato acordado.',[7]),
q('Retención','El servidor elimina las claves de idempotencia después de 24 horas. Llega un reintento a las 30 horas. ¿Qué riesgo debe documentarse?',['El ETag lo cubre siempre','Se conserva automáticamente para siempre','No existe riesgo','Puede volver a procesarse si no hay otra protección'],3,'La protección depende de la ventana de retención. Una clave olvidada puede tratarse como nueva; documentar esta ventana es parte del contrato y del diseño de reintentos.',[14])]},
{semana:7,titulo:'UX y decisiones de experiencia',archivo:'Semana7-Presentacion-Analisis-Sistemas-II-037.pdf',preguntas:[
q('UX y UI','La app se ve bonita, pero el asesor pierde datos cuando se corta la señal. ¿Qué conclusión corresponde?',['La UX es buena porque el color es correcto','La apariencia no garantiza una buena experiencia completa','Solo importa la tipografía','Es un problema ajeno al usuario'],1,'UX incluye lo que la persona hace y percibe para alcanzar su objetivo, antes, durante y después. UI es la superficie de interacción; una falla del recorrido puede arruinar la experiencia aunque la pantalla sea atractiva.',[6,8]),
q('Garrett','Se investiga por qué el asesor necesita completar cobros rápidamente en campo. ¿Qué plano se trabaja?',['Superficie','Esqueleto','Estrategia','Alcance'],2,'Estrategia relaciona las necesidades del usuario con los objetivos del negocio. El alcance decidirá funciones concretas; todavía se está entendiendo el objetivo.',[7]),
q('Garrett','Se decide incluir la función de registrar pagos sin conexión. ¿Qué plano define esa función?',['Alcance','Superficie','Esqueleto','Solo tipografía'],0,'Alcance delimita funciones y contenidos. Su flujo se definirá en estructura, su disposición en esqueleto y su apariencia en superficie.',[7]),
q('Garrett','Se decide el recorrido cliente → crédito → revisión → confirmación. ¿Qué plano predomina?',['Superficie','Estrategia','Esqueleto','Estructura'],3,'Estructura organiza la información y la interacción entre pasos. Esqueleto define dónde se ubican los controles dentro de esas pantallas.',[7]),
q('Garrett','Ubicar el botón Confirmar debajo del monto corresponde a…',['Alcance','Esqueleto','Estrategia','Superficie únicamente'],1,'Esqueleto se ocupa de la disposición y jerarquía de controles e información. Decidir el color y la tipografía del botón sería superficie.',[7]),
q('Investigación','El asesor afirma que nunca pierde información, pero usa un cuaderno auxiliar durante las visitas. ¿Qué método permite conocer ese trabajo real?',['Solo una encuesta de colores','Inventar una persona','Observación contextual y revisión de artefactos','Preguntar si le gusta nuestra app'],2,'Observar el contexto y revisar cuadernos revela prácticas y soluciones informales que las entrevistas pueden omitir. La investigación debe fundamentar las decisiones con evidencia.',[11]),
q('Personas','El equipo inventa edad y aficiones de un usuario sin investigar. ¿Qué le falta a esa persona?',['Evidencia sobre objetivos, frustraciones y contexto de usuarios reales','Un avatar más bonito','Más datos demográficos inventados','Una preferencia de color'],0,'Una persona es un arquetipo basado en datos, no un personaje decorativo ni un promedio demográfico. Debe ayudar a tomar decisiones de diseño.',[13,14]),
q('Escenario','¿Cuál es un escenario útil para diseñar?',['El usuario pulsa A, luego B','La pantalla es azul','El sistema contiene cinco botones','Byron cobra en un mercado sin señal y necesita entregar evidencia del pago'],3,'Un escenario expresa persona, objetivo, contexto y obstáculo, sin imponer todavía botones o solución. Esto permite evaluar distintas interfaces para la misma necesidad.',[16]),
q('Journey map','El mapa solo enumera pantallas y dice que el usuario se frustra. ¿Qué mejora necesitas?',['Agregar más colores','Identificar dolor concreto y oportunidad en cada etapa','Eliminar emociones','Convertirlo en un listado de endpoints'],1,'El journey incluye etapas, acciones, contactos, pensamientos, emociones, dolores y oportunidades. Un dolor concreto sería recapturar el DPI tras perder sesión; permite proponer una solución verificable.',[17,18]),
q('Fintech','Se captura Q8,000 en lugar de Q800 y el backend calcula correctamente. ¿Qué evidencia el caso?',['La precisión decimal resuelve todo','El usuario no necesita revisar','La captura y confirmación son parte de la prevención de errores financieros','UX solo cambia colores'],2,'Un cálculo correcto sobre datos equivocados sigue causando daño. Unidades claras, montos legibles y confirmación ayudan a evitar una operación errónea.',[8,19]),
q('Calculadora: mora','Según el ejemplo del PDF, capital en mora Q725.76 y 45 días: 30 días al 18% anual y 15 al 24%, base 360. ¿Cuánto corresponde redondeando al final?',['Q18.14','Q21.77','Q10.89','Q32.66'],0,'Tramo 1: 725.76 × (0.18/360) × 30 = 10.8864. Tramo 2: 725.76 × (0.24/360) × 15 = 7.2576. Suma sin redondeos intermedios: 18.1440. Resultado final: Q18.14. No se aplican 45 días completos a la tasa del segundo tramo.',[24]),
q('Cambio de política','Se adopta mora escalonada, pero los créditos ya otorgados deben conservar sus reglas. ¿Qué diseño apoya esa evolución?',['Reemplazar la tasa de todos los créditos','Reescribir pruebas para ocultar diferencias','Tomar siempre la última política','Políticas versionadas y una estrategia sustituible respetando la asignada a cada crédito'],3,'La nueva política no debe alterar retroactivamente créditos anteriores. El material usa el cambio para evaluar abierto/cerrado: incorporar una implementación sin modificar la calculadora ni romper las pruebas existentes.',[24,25])]},
{semana:8,titulo:'UI, Nielsen y accesibilidad',archivo:'Semana8-Presentacion-Analisis-Sistemas-II-037.pdf',preguntas:[
q('Design tokens','Cinco pantallas usan tonos diferentes para la misma alerta. ¿Qué corrige la inconsistencia?',['Copiar los colores a mano','Definir un token semántico común y reutilizarlo','Usar rojo en todo','Eliminar todas las alertas'],1,'Un token nombra una decisión visual y concentra su valor. Un sistema de diseño añade componentes, variantes, estados y reglas de uso para sostener la consistencia.',[4,7]),
q('Estados','Una pantalla se diseñó únicamente con datos cargados. ¿Qué falta contemplar?',['Solo el logo','Nada','Vacío, cargando, error y éxito','Solo un fondo distinto'],2,'Los cuatro estados permiten orientar al usuario durante todo el proceso. Una falla debe explicar qué pasó y cómo continuar, sin depender de un mensaje técnico críptico.',[8]),
q('Nielsen 1','Después de pulsar Registrar pago no aparece ninguna señal de actividad. ¿Qué heurística se incumple principalmente?',['Visibilidad del estado del sistema','Ayuda y documentación','Diseño minimalista','Correspondencia con el mundo real'],0,'El usuario debe saber si se está guardando y si terminó. Conviene distinguir en proceso, confirmado y fallido; la respuesta visible también debe ser accesible para tecnologías de asistencia.',[14,23]),
q('Nielsen 2','Una clienta no entiende el rótulo devengo moratorio. ¿Qué cambio responde a correspondencia con el mundo real?',['Agregar más siglas','Ocultar el valor','Cambiar solo el color','Usar lenguaje como recargo por atraso y explicar el desglose'],3,'La interfaz debe hablar en el vocabulario del usuario. Aclarar conceptos ayuda a entender la deuda y tomar decisiones.',[14]),
q('Nielsen 6','Para confirmar un pago se exige recordar el saldo de otra pantalla. ¿Qué mejora encaja?',['Memorizar el número','Mostrar saldo y desglose junto a la confirmación','Agregar un temporizador','Ocultar información'],1,'Reconocer antes que recordar reduce la carga de memoria. La información necesaria debe estar disponible en el momento de decidir.',[15]),
q('Evaluación','Una auditoría automática no encuentra fallas. ¿Puede concluirse que la interfaz es usable y accesible?',['Sí, siempre','Sí, si tiene colores bonitos','No; se requieren recorridos manuales y evaluación heurística','Solo hace falta otra captura'],2,'El material combina herramientas con teclado, lector de pantalla y tareas reales. La evaluación heurística y la auditoría WCAG se complementan y no quedan resueltas por un único reporte automático.',[12,26,27]),
q('Contraste','Un texto normal tiene contraste 3.41:1. Según el umbral AA del material, ¿cumple?',['No; requiere al menos 4.5:1','Sí; todo valor mayor que 3 cumple para texto normal','Sí; basta 2:1','No; siempre requiere 21:1'],0,'El material establece 4.5:1 para texto normal y 3:1 para texto grande. Comparar un ratio ya calculado no requiere calcular luminancias.',[5,21]),
q('POUR','El estado moroso se comunica únicamente por rojo. ¿Qué corrección mejora su percepción?',['Un rojo más intenso sin texto','Una animación sin etiqueta','Un sonido obligatorio','Agregar una etiqueta textual o símbolo con significado accesible'],3,'La información no debe depender solo del color. Una señal adicional permite identificar el estado aunque no se distingan los tonos; corresponde al principio Perceptible.',[6,18]),
q('Objetivos táctiles','Un botón mide 20×20 px CSS, está pegado a otros controles y el caso no admite excepciones de tamaño o espaciado. ¿Cumple el mínimo de 24×24 indicado en clase?',['Sí, por ser cuadrado','No; ampliar el área interactiva al menos a 24×24','Sí, si el icono es claro','Sí, si funciona con ratón'],1,'20 es menor que 24 en ambas dimensiones. Se evalúa el objetivo interactivo, no solamente el dibujo del icono. El enunciado excluye excepciones para que el diagnóstico sea inequívoco.',[20]),
q('Teclado','Una barra fija tapa por completo el control que tiene el foco. ¿Qué criterio nuevo del PDF corresponde?',['1.4.3 Contraste','3.2.6 Ayuda consistente','2.4.11 Focus Not Obscured (Minimum)','3.3.7 Entrada redundante'],2,'El usuario necesita localizar el elemento que recibe la interacción de teclado. La barra no debe ocultarlo por completo; hay que ajustar desplazamiento o disposición.',[20]),
q('Transacciones','¿Qué mecanismo corresponde al criterio 3.3.4 en una operación financiera?',['Que sea reversible, verificada o confirmada','Usar siempre color verde','Exigir doble clic sin explicación','Mostrar solo Error 500'],0,'El material relaciona la prevención de errores con revisión y confirmación de montos y con reversión cuando sea posible. No exige necesariamente las tres alternativas simultáneamente.',[9,21]),
q('Severidad','Un defecto impide completar el pago sin alternativa. ¿Qué severidad sería razonable, si se justifica ese impacto?',['0, no es problema','1, cosmético','2, menor','4, catastrófico'],3,'La escala va de 0 a 4. Un bloqueo de la tarea crítica puede justificar 4, pero el informe debe aportar evidencia, ubicación e impacto, además de una corrección concreta.',[16])]},
{semana:9,titulo:'Movilidad, web y revisión de diseño',archivo:'Semana9_Presentacion.pdf',preguntas:[
q('Arquitectura móvil','Asesores necesitan bajo costo, actualizaciones rápidas y operación offline razonable, sin hardware especial. Según la comparación del PDF, ¿qué candidata analizarías primero?',['Nativa obligatoria','PWA','Solo escritorio','Una app sin almacenamiento local'],1,'La PWA reutiliza la web y se distribuye por URL. La elección debe confirmarse contra contexto y capacidades requeridas; no basta con llamarla PWA para que funcione sin conexión.',[3,6]),
q('Hardware','Un cobro depende de hardware que la PWA no cubre adecuadamente en los dispositivos objetivo. ¿Qué harías?',['Ignorar el requisito','Elegir por moda','Evaluar nativa o híbrida y comprobar soporte del hardware','Eliminar las pruebas en dispositivos'],2,'El material presenta la PWA como candidata condicionada por los requisitos. Acceso a hardware, presupuesto, conectividad y distribución forman parte de la decisión.',[6,14]),
q('PWA','¿Qué pieza intercepta solicitudes y permite servir recursos guardados cuando no hay red?',['Service Worker','Solo manifest.json','Una media query','Un archivo README'],0,'El service worker puede interceptar peticiones y aplicar estrategias de caché. Hay que implementar esas estrategias y preparar recursos; el archivo manifest no hace ese trabajo.',[7]),
q('Manifest','¿Qué responsabilidad tiene el manifiesto de una PWA?',['Calcular mora','Evitar cobros duplicados','Sincronizar pagos por sí solo','Declarar identidad de la app, iconos y presentación para su instalación'],3,'El manifest aporta metadatos de instalación y apariencia. El trabajo sin conexión y la sincronización requieren otras piezas; no se obtienen solo por declarar el nombre de la app.',[7]),
q('Offline','El asesor registra un pago sin señal. ¿Qué solución completa se aproxima al diseño del material?',['Mostrar confirmado aunque no se haya enviado','Guardar una acción pendiente y sincronizar con idempotencia','Descartar el pago','Depender solo de CSS'],1,'La cola local conserva acciones hasta recuperar red; la clave de idempotencia evita aplicar otra vez una misma intención. La UI debe diferenciar pendiente de confirmación del servidor.',[7,12]),
q('Fecha de corte','Un pago capturado ayer se sincroniza hoy. ¿Cómo evita el diseño calcular mora usando ciegamente el reloj del teléfono?',['Usar siempre la hora local','Borrar la fecha de pago','Usar una fecha de corte explícita y el puerto Reloj del diseño','Aplicar siempre un día extra'],2,'El material exige que la fecha de corte sea un parámetro y no un hoy implícito del dispositivo. La política debe definir qué fecha corresponde a la operación.',[12]),
q('Responsive','¿Qué conjunto de técnicas presenta la sesión para diseño responsivo?',['Cuadrículas fluidas, media queries e imágenes flexibles','Ancho fijo para todo','Una captura por dispositivo','Solo reducir la fuente'],0,'Las columnas fluidas adaptan el espacio; las media queries cambian la composición y las imágenes flexibles evitan desbordamiento. El ejemplo usa una, dos y más columnas según el ancho.',[8]),
q('Mobile-first','¿Qué significa empezar por móvil para Byron?',['Ocultar funciones al final','Diseñar solo para un teléfono costoso','Hacer los botones más pequeños','Priorizar lo esencial en pantalla pequeña, una mano y señal débil'],3,'Mobile-first comienza por las restricciones reales y luego enriquece el diseño para más espacio o capacidad. No consiste únicamente en reducir una pantalla de escritorio.',[9]),
q('Mejora progresiva','¿En qué orden construye capas la presentación?',['JavaScript → CSS → contenido','Contenido → estructura → presentación → comportamiento','Animaciones → iconos → servidor','Solo JavaScript'],1,'Cada capa debe aportar mejoras sin que la información esencial dependa de la siguiente. Esto no significa que una transacción offline pueda completarse sin lógica ni infraestructura; hay que diseñar explícitamente esa capacidad.',[10,11]),
q('Perfiles','¿Qué experiencia necesita principalmente gerencia frente al asesor de campo?',['La misma pantalla sin cambios','Botones sin cifras','Información agregada con contexto y aprovechamiento del escritorio','Ocultar los castigos'],2,'Gerencia decide con cifras agregadas en pantalla grande; el asesor necesita una captura ágil en campo. El diseño responde a objetivos distintos sin confundir indicadores.',[13]),
q('Design Review','Durante la revisión, el autor explica cada botón al equipo evaluador. ¿Qué debe cambiar?',['Guardar silencio y observar cómo resuelven los flujos','Dar una explicación más larga','Resolver los flujos por el evaluador','Evaluar solo colores'],0,'La regla del silencio permite detectar dificultades que el autor compensaría con ayuda. Se necesita un prototipo navegable y observación de tareas reales.',[17,18]),
q('Hallazgos','Tras el review, ¿qué tratamiento es correcto?',['Ignorar lo que incomoda','Aceptar todo sin analizar','Escribir solamente se ve confuso','Registrar síntoma, criterio, severidad y decidir justificadamente qué incorporar'],3,'El informe debe describir evidencia concreta. Se puede rechazar un hallazgo con argumentos, pero no ignorarlo; las correcciones se relacionan con los problemas observados.',[17,19])]},
];
export const talleres = [
{titulo:'1. Sustituir condicionales con Strategy',paginas:[21,24,25],reto:'La calculadora decide internamente qué regla de mora ejecutar. Refactoriza para recibir una estrategia; conserva los resultados de las reglas ya existentes y deja las tasas en una política externa. Escribe la interfaz, dos implementaciones y el consumidor.',antes:`class Calculadora {
  calcular(tipo: string, capital: Dinero, dias: number): Dinero {
    if (tipo === 'fija') return calcularFija(capital, dias, politicaFija);
    if (tipo === 'tramos') return calcularTramos(capital, dias, politicaTramos);
    throw new Error('Política desconocida');
  }
}`,despues:`// Esquema TypeScript: Dinero, Politica y los cálculos
// son contratos del dominio existentes, no flotantes monetarios.
interface EstrategiaMora {
  calcular(capital: Dinero, dias: number): Dinero;
}
class MoraFija implements EstrategiaMora {
  constructor(private readonly politica: PoliticaFija) {}
  calcular(capital: Dinero, dias: number): Dinero {
    return calcularFija(capital, dias, this.politica);
  }
}
class MoraPorTramos implements EstrategiaMora {
  constructor(private readonly politica: PoliticaTramos) {}
  calcular(capital: Dinero, dias: number): Dinero {
    return calcularTramos(capital, dias, this.politica);
  }
}
class Calculadora {
  constructor(private readonly estrategia: EstrategiaMora) {}
  calcular(capital: Dinero, dias: number): Dinero {
    return this.estrategia.calcular(capital, dias);
  }
}
// La composición selecciona según la política del crédito.
const calculadora = new Calculadora(new MoraFija(politicaFija));`,explicacion:'La calculadora deja de conocer tipos concretos. La selección se mueve al punto de composición; no desaparece mágicamente del sistema. Strategy encaja porque varía el algoritmo. Factory podría complementar la creación, pero no sustituye el contrato de comportamiento. Las funciones existentes se conservan para no alterar resultados. Para mora por tramos, redondea solo al final y respeta la política histórica del crédito.',rubrica:['Interfaz común y consumidor que depende de ella.','Implementaciones independientes y políticas recibidas como datos.','Mismos resultados para los casos anteriores, sin modificar sus pruebas para ocultar errores.','Explicación de Strategy frente a Factory y de la selección fuera de la calculadora.']},
{titulo:'2. Componer cargos con Decorator',paginas:[18,24],reto:'Una cuota base admite seguro y gasto de gestión fijo, opcionales y combinables. El código agrega una subclase para cada combinación. Reemplaza esa jerarquía por composición. Los cargos de este ejercicio son montos ya calculados y de la misma moneda.',antes:`class CuotaConSeguro extends CuotaBase { /* ... */ }
class CuotaConGestion extends CuotaBase { /* ... */ }
class CuotaConSeguroYGestion extends CuotaBase { /* ... */ }`,despues:`interface Cuota { monto(): Dinero; }
class CuotaBase implements Cuota {
  constructor(private readonly valor: Dinero) {}
  monto(): Dinero { return this.valor; }
}
class ConCargo implements Cuota {
  constructor(
    private readonly interna: Cuota,
    private readonly cargo: Dinero
  ) {}
  monto(): Dinero { return this.interna.monto().mas(this.cargo); }
}
const cuota: Cuota = new ConCargo(
  new ConCargo(new CuotaBase(base), seguro), gestion
);`,explicacion:'CuotaBase y ConCargo cumplen la misma interfaz. Cada envoltorio delega al objeto interno y añade un cargo; así se evitan clases para todas las combinaciones. Se asume Dinero inmutable con validación de moneda. El ejercicio suma cargos fijos: calcular intereses sobre otros cargos o definir prelación de un pago son reglas diferentes que este ejemplo no implementa.',rubrica:['Base y decorador cumplen el mismo contrato.','El decorador recibe y delega a otra Cuota.','Composición de dos cargos sin crear una clase para la combinación.','No usar flotantes monetarios ni confundir total con prelación del pago.']},
{titulo:'3. Desacoplar reacciones con Observer',paginas:[22,24],reto:'MotorDeMora conoce las clases de correo, tablero y auditoría. Refactoriza para permitir incorporar otro receptor sin editar el motor. Explica además qué no garantiza un Observer en memoria.',antes:`class MotorDeMora {
  registrarEntrada(evento: EventoMora): void {
    correo.enviar(evento);
    tablero.actualizar(evento);
    auditoria.registrar(evento);
  }
}`,despues:`interface ObservadorMora {
  alEntrarEnMora(evento: EventoMora): void;
}
class MotorDeMora {
  private readonly observadores: ObservadorMora[] = [];
  suscribir(observador: ObservadorMora): void {
    this.observadores.push(observador);
  }
  registrarEntrada(evento: EventoMora): void {
    for (const observador of this.observadores) {
      observador.alEntrarEnMora(evento);
    }
  }
}
class AuditorMora implements ObservadorMora {
  constructor(private readonly auditoria: Auditoria) {}
  alEntrarEnMora(evento: EventoMora): void {
    this.auditoria.registrar(evento);
  }
}
motor.suscribir(new AuditorMora(auditoria));
// Correo y tablero se adaptan al mismo contrato.`,explicacion:'El motor depende de ObservadorMora y publica sin conocer el trabajo de cada suscriptor. Este esquema ilustra el desacoplamiento del PDF; no es una infraestructura de mensajería durable. Deben definirse errores de receptores, duplicados y persistencia según los requisitos. Tampoco hay que emitir entrada en mora repetidamente si solo se vuelve a consultar una cuota ya morosa.',rubrica:['Lista de suscriptores tipada con una interfaz.','Reacciones concretas fuera del motor.','Nuevo receptor agregado desde la composición sin editar el publicador.','Diferenciar notificación en memoria de garantías de entrega y controlar eventos duplicados.']}
];
