import { mkdir, writeFile } from 'node:fs/promises';
import { examenes, talleres } from './banco.mjs';
const dir = 'analisis-de-sistema';
const esc = s => String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const ref = (e, paginas) => `<p class="fuente">Base: ${esc(e.archivo)} · página${paginas.length > 1 ? 's' : ''} ${paginas.join(', ')} del archivo PDF.</p>`;
const nav = actual => `<nav aria-label="Exámenes por semana"><a href="index.html" ${actual===0?'aria-current="page"':''}>Inicio</a>${examenes.map(e=>`<a href="semana-${e.semana}.html" ${actual===e.semana?'aria-current="page"':''}>Semana ${e.semana}</a>`).join('')}<a href="refactorizacion.html" ${actual===10?'aria-current="page"':''}>Taller de código</a></nav>`;
const layout = (titulo, contenido, actual=0, raiz=false) => `<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(titulo)} · Análisis de Sistemas II</title><meta name="description" content="Practica con casos fintech, preguntas explicadas y referencias a las semanas 5 a 9."><link rel="icon" href="${raiz?dir+'/':''}favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="${raiz?dir+'/':''}estilos.css"><script src="${raiz?dir+'/':''}examen.js" defer></script></head>
<body><a class="saltar" href="#contenido">Saltar al contenido</a><header><div class="marca"><span class="logo" aria-hidden="true">AS</span><div>ANÁLISIS DE SISTEMAS II<small>Cuaderno de práctica · Módulo II</small></div></div>${raiz?'':nav(actual)}</header><main id="contenido">${contenido}</main><footer>Casos de práctica originales basados en las presentaciones proporcionadas. No es el examen oficial. Las referencias usan la posición de página en el PDF, que puede diferir del número impreso.</footer></body></html>`;
await mkdir(dir,{recursive:true});
const inicio = `<div class="encabezado"><p class="etiqueta">TU SESIÓN DE ESTUDIO</p><h1>Entiende el caso.<br>Justifica la solución.</h1><p>Elige una semana, responde y revisa por qué funciona cada respuesta. Luego lleva los patrones a código fintech.</p></div><div class="resumen"><span><strong>5</strong> exámenes</span><span><strong>60</strong> preguntas</span><span><strong>3</strong> refactorizaciones</span></div><section class="rejilla" aria-label="Elegir examen">${examenes.map(e=>`<a class="tarjeta enlace" href="semana-${e.semana}.html"><span class="etiqueta">SEMANA ${e.semana}</span><h2>${e.titulo}</h2><p>12 preguntas · nota de práctica sobre 15</p><span class="ir">Resolver examen →</span></a>`).join('')}<a class="tarjeta enlace especial" href="refactorizacion.html"><span class="etiqueta">APLICACIÓN FINTECH</span><h2>Del problema al código</h2><p>Strategy, Decorator y Observer: escribe tu propuesta y compárala con la solución razonada.</p><span class="ir">Abrir taller →</span></a></section><aside class="nota"><h2>¿Para qué llevar calculadora?</h2><p>La Semana 7 incluye mora escalonada: se suman los importes de los tramos recorridos y se redondea una sola vez al final. La pregunta 11 reproduce el cálculo del PDF. Es contenido explícito del material; no podemos asegurar qué elegirá el docente para el examen.</p></aside>`;
await writeFile(`${dir}/index.html`,layout('Inicio',inicio));
await writeFile('index.html',layout('Exámenes de práctica',`<div class="encabezado"><p class="etiqueta">SEMANAS 5 A 9</p><h1>Análisis de Sistemas II</h1><p>Cinco exámenes con casos, respuestas explicadas y un taller de refactorización fintech.</p><a class="boton" href="${dir}/index.html">Entrar a los exámenes →</a></div>`,0,true));
for (const e of examenes) {
  const preguntas = e.preguntas.map((q,i)=>`<article class="pregunta" data-correcta="${q.correcta}"><p class="etiqueta">${String(i+1).padStart(2,'0')} / 12 · ${esc(q.tema)}</p><fieldset><legend>${esc(q.pregunta)}</legend>${q.opciones.map((o,j)=>`<label class="opcion"><input type="radio" name="p${i}" value="${j}"><span><b>${'ABCD'[j]}.</b> ${esc(o)}</span></label>`).join('')}</fieldset><p class="resultado-item" aria-live="polite"></p><details class="solucion"><summary>Ver respuesta y explicación</summary><div class="explicacion"><p><strong>Respuesta ${'ABCD'[q.correcta]}: ${esc(q.opciones[q.correcta])}</strong></p><p>${esc(q.explicacion)}</p>${ref(e,q.paginas)}</div></details></article>`).join('');
  const contenido = `<div class="encabezado"><p class="etiqueta">EXAMEN · SEMANA ${e.semana}</p><h1>${esc(e.titulo)}</h1><p>Responde las 12 preguntas. Cada acierto vale 1.25 puntos; las omitidas valen 0. Las explicaciones están disponibles para estudiar, pero consultarlas no cuenta como acierto.</p></div><noscript><p class="nota">Puedes responder en papel y abrir las explicaciones. Activa JavaScript para obtener la calificación automática.</p></noscript><form id="examen"><div class="barra"><p id="avance" role="status">0 de 12 respondidas</p><button type="submit">Calificar examen</button><button type="button" class="secundario" id="reiniciar">Reiniciar</button></div><section id="nota-final" class="nota" tabindex="-1" hidden aria-label="Resultado del examen"></section>${preguntas}<div class="barra"><button type="submit">Calificar examen</button><a href="index.html">Elegir otra semana</a></div></form>${e.semana===5?'<aside class="nota"><h2>Ahora refactoriza</h2><p>Practica con código inicial y soluciones comentadas.</p><a href="refactorizacion.html">Ir al taller de código →</a></aside>':''}`;
  await writeFile(`${dir}/semana-${e.semana}.html`,layout(e.titulo,contenido,e.semana));
}
await writeFile(`${dir}/refactorizacion.html`,layout('Taller de refactorización',`<div class="encabezado"><p class="etiqueta">TALLER · SEMANA 5 + APLICACIÓN</p><h1>Refactorizar con propósito</h1><p>Identifica el problema, escribe tu solución y compárala con la propuesta. Los fragmentos son esquemas didácticos TypeScript con contratos del dominio; no son un sistema financiero ejecutable.</p><p>Autoevaluación: un punto por criterio de la rúbrica. Estas respuestas abiertas no reciben una nota automática. Tu texto permanece solo en esta página y se pierde al recargar.</p></div>${talleres.map((t,i)=>`<article class="pregunta"><h2>${t.titulo}</h2><p>${esc(t.reto)}</p><h3>Código inicial</h3><pre tabindex="0" aria-label="Código inicial del ejercicio ${i+1}"><code>${esc(t.antes)}</code></pre><label class="campo" for="propuesta-${i}">Tu propuesta y justificación</label><textarea id="propuesta-${i}" rows="9" spellcheck="false" placeholder="Explica qué cambia, qué se conserva y por qué elegiste ese patrón."></textarea><details><summary>Comparar con la solución y rúbrica</summary><div class="explicacion"><h3>Propuesta de refactorización</h3><pre tabindex="0" aria-label="Solución del ejercicio ${i+1}"><code>${esc(t.despues)}</code></pre><p>${esc(t.explicacion)}</p><h3>Rúbrica: 4 puntos</h3><ul>${t.rubrica.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${ref(examenes[0],t.paginas)}</div></details></article>`).join('')}`,10));
console.log('Generados: portada, inicio, 5 exámenes y taller. 60 preguntas y 3 refactorizaciones.');
